version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: order_db
      DB_USERNAME: postgres
      DB_PASSWORD: password
      MANAGEMENT_SERVER_PORT: 8081
      SERVER_PORT: 8080
    depends_on:
      - db
