version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db

  app:
    image: 122610499913.dkr.ecr.us-east-1.amazonaws.com/process-order-service:latest
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: order_db
      DB_USERNAME: postgres
      DB_PASSWORD: password
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
